### ISSUE TITLE
fix: Category Response

### ISSUE THREAD

**Issue by PandaHun** [GreenByMe/GreenByMe_Server#101]
- Category Integer 속성 추가

all: 0 
energy: 1 
...

- All, NONE ... 순으로

**Comment by Livenow14** [comment]
ChangeLog 종류: api response, (/api/categorys)
Category Integer 속성 추가. 
및 response 값 변경

변경 전 
{
  "categorys": {
    "ALL": 
    "NONE": 
    "ENERGY": 
    "DISPOSABLE": 
    "TRAFFIC": 
    "WATERWORKS": 
    "CAMPAIGN": 
  }
}

변경 후
{
  "enums": {
    "ALL": 0,
    "NONE": 1,
    "ENERGY": 2,
    "DISPOSABLE": 3,
    "TRAFFIC": 4,
    "WATERWORKS": 5,
    "CAMPAIGN": 6
  }
}

**Comment by Livenow14** [comment]
ChangeLog 
종류: api response, (/api/categorys/certificate/counts)

변경 전
{
  "certificatecounts": {
    "ONE_DAY": 1,
    "ONE_TIMES_A_WEEK": 1,
    "TWO_TIMES_A_WEEK": 2,
    "THREE_TIMES_A_WEEK": 3,
    "ALL_TIMES_A_WEEK": 7,
    "ONE_TIMES_A_WEEK_MONTH": 4,
    "TWO_TIMES_A_WEEK_MONTH": 8,
    "THREE_TIMES_A_WEEK_MONTH": 12,
    "ALL_TIMES_A_WEEK_MONTH": 28
  }
}

변경 후
{
  "enums": {
    "ONE_DAY": 1,
    "ONE_TIMES_A_WEEK": 1,
    "TWO_TIMES_A_WEEK": 2,
    "THREE_TIMES_A_WEEK": 3,
    "ALL_TIMES_A_WEEK": 7,
    "ONE_TIMES_A_WEEK_MONTH": 4,
    "TWO_TIMES_A_WEEK_MONTH": 8,
    "THREE_TIMES_A_WEEK_MONTH": 12,
    "ALL_TIMES_A_WEEK_MONTH": 28
  }
}

**Comment by Livenow14** [comment]
ChangeLog
종류: api response, (/api/categorys/days)

변경 전
{
  "days": {
    "DAY": 1,
    "WEEK": 7,
    "MONTH": 30
  }
}
변경 후
{
  "enums": {
    "DAY": 1,
    "WEEK": 7,
    "MONTH": 30
  }
}
