### ISSUE TITLE
fix : [/api/missions/categorys/{category}/daycategory/{datCategory}] mission api need to combine

### ISSUE THREAD

**Issue by PsPLoG** [GreenByMe/GreenByMe_Server#107]
/api/missions
findAllMission

/api/missions/categorys/{category}
findAllByCategory

/api/missions/categorys/{category}/daycategory/{datCategory}
findAllByCategoryAndDayCategory

여기서에서 all카테고리가 존재하는데 의미대로 작동하지 않습니다

그런데 수정하게되면 세api가 중복되니  통합하는게 더 좋을 것 같습니다

**Comment by Livenow14** [comment]
/api/missions
findAllMission
--삭제

/api/missions/categorys/{category}
findAllByCategory
--삭제


/api/missions/categorys/{category}/daycategory/{datCategory}
findAllByCategoryAndDayCategory
--유지 및 sort옵션 추가.
