### ISSUE TITLE
fix : Post Image permission denied

### ISSUE THREAD

**Issue by PsPLoG** [GreenByMe/GreenByMe_Server#139]
https://cafecube.iptime.org/api/posts/images/36abd923-fca4-43d4-b677-ca59ff4feb8d_JPEG_20201005_143456_881704836440466011.jpg
{"message":"권한이 없습니다","status":401,"errors":[],"code":"U_006"}
이렇게 나오네요

**Comment by Livenow14** [comment]
완료
