### ISSUE TITLE
안쓰는 변수들 제거

### ISSUE THREAD

**Issue by PsPLoG** [GreenByMe/GreenByMe_Server#30]
data class MainMissionDAO(
    val content: List<Content>,
    val empty: Boolean,
    val first: Boolean,
    val last: Boolean,
    val number: Int,
    val numberOfElements: Int,
    val pageable: Pageable,
    val size: Int,
    val sort: Sort,
    val totalElements: Int,
    val totalPages: Int
) {
    data class Content(
        val category: String,
        val dayCategory: String,
        val description: String,
        val endDate: String,
        val id: Int,
        val passCandidates: Int,
        val pictureUrl: String,
        val startDate: String,
        val subject: String
    )

    data class Pageable(
        val offset: Int,
        val pageNumber: Int,
        val pageSize: Int,
        val paged: Boolean,
        val sort: Sort,
        val unpaged: Boolean
    ) {
        data class Sort(
            val empty: Boolean,
            val sorted: Boolean,
            val unsorted: Boolean
        )
    }

    data class Sort(
        val empty: Boolean,
        val sorted: Boolean,
        val unsorted: Boolean
    )
}

**Comment by Livenow14** [comment]
안쓰는 변수들이 pageble 저거 말하는거야 ?
