### ISSUE TITLE
fix: User_Id request API

### ISSUE THREAD

**Issue by Livenow14** [GreenByMe/GreenByMe_Server#64]
- [PUT ]/api/users/image

- [PUT ]/api/users/nickname

**Comment by PandaHun** [comment]
User Information 수정 말하는 건가요

**Comment by Livenow14** [comment]
아직 User_id 를 받는 api들이 있습니다~ 
토큰으로 받게 변경해주세요

**Comment by PsPLoG** [comment]
/api/posts
이거도 수정해주세요

**Comment by PandaHun** [comment]
Solved
