### ISSUE TITLE
fix :  mission, missionInfos detail result unification

### ISSUE THREAD

**Issue by PsPLoG** [GreenByMe/GreenByMe_Server#67]
**mission result**
/api/missions/{mission_id}
{
  "category": "NONE",
  "dayCategory": "DAY",
  "description": "string",
  "endDate": "2020-08-12T16:16:31.063Z",
  "expectCo2": 0,
  "expectTree": 0,
  "id": 0,
  "missionCertificationMethod": {
    "missionCertificateCount": "ONE_DAY",
    "text": "string",
    "title": "string"
  },
  "passCandidatesCount": 0,
  "pictureUrl": "string",
  "progressByMissionId": 0,
  "startDate": "2020-08-12T16:16:31.063Z",
  "subject": "string"
}

**missionInfos result**
/api/missionInfos/{missionInfo_id}
{
  "endDate": "2020-08-12T16:13:25.813Z",
  "finishCount": 0,
  "missionDetailsDto": {
    "category": "NONE",
    "dayCategory": "DAY",
    "description": "string",
    "expectCo2": 0,
    "expectTree": 0,
    "id": 0,
    "missionCertificationMethod": {
      "missionCertificateCount": "ONE_DAY",
      "text": "string",
      "title": "string"
    },
    "subject": "string"
  },
  "missionInfoStatus": "FINISH",
  "progress": 0,
  "remainPeriod": {
    "remainDay": 0,
    "remainHour": 0,
    "remainMin": 0
  },
  "startDate": "2020-08-12T16:13:25.813Z",
  "userNickName": "string"
}

비슷한 API이지만
결과값의 형태가 다름

**Comment by Livenow14** [comment]
mission_info에서 계속 헷갈리는거 같은데,
 테이블명 어떻게 하는게 좋을까요?

**Comment by PsPLoG** [comment]
persnal_mission정도?

**Comment by Livenow14** [comment]
ChangeLog 
종류: api response, api request, api path, naming 

# 변경 전 
1. MissionInfo 
2. path: /api/missionInfos
3.{
"endDate": "2020-08-12T16:13:25.813Z",
"finishCount": 0,
"missionDetailsDto": {
"category": "NONE",
"dayCategory": "DAY",
"description": "string",
"expectCo2": 0,
"expectTree": 0,
"id": 0,
"missionCertificationMethod": {
"missionCertificateCount": "ONE_DAY",
"text": "string",
"title": "string"
},
"subject": "string"
},
"missionInfoStatus": "FINISH",
"progress": 0,
"remainPeriod": {
"remainDay": 0,
"remainHour": 0,
"remainMin": 0
},
"startDate": "2020-08-12T16:13:25.813Z",
"userNickName": "string"
}


# 변경 후
1. PersonalMission
2. path: /api/personalMissions
3.{
  "userNickName": "민석굴암",
  "mission_id": 1,
  "finishCount": 1,
  "progress": 0,
  "remainPeriod": {
    "remainDay": 0,
    "remainHour": 23,
    "remainMin": 54
  },
  "startDate": "2020-08-20T20:49:25.639",
  "endDate": "2020-08-21T20:49:25.639",
  "personalMissionStatus": "IN_PROGRESS"
}
