### ISSUE TITLE
feat: EntityListener 등록 

### ISSUE THREAD

**Issue by Livenow14** [GreenByMe/GreenByMe_Server#89]
실제 서비스시 log를 통해 에러 헨들링을 진행해야 할거 같아서 적용하려 함.
각 엔티티 생생/변경 이벤트 마다 log넣는게 비효율적이라 생각하여 
리스너를 이용해보려 함. 
추가 의견 부탁함.

**Comment by PandaHun** [comment]
추가해주세요
