### ISSUE TITLE
fix: User Update API

### ISSUE THREAD

**Issue by PandaHun** [GreenByMe/GreenByMe_Server#99]

**Comment by Livenow14** [comment]
ChangeLog 
종류: api response, api request, api path, naming 

변경 전
[PUT]/api/users/nickname

 변경 후
[PUT]/api/users
{
file
file(formData) | file

jwt 
*string(header) | JWT Token

nickName
string(query) |  
}

**Comment by Livenow14** [comment]
ChangeLog
종류: api response, api request, api path, naming

변경 전
[PUT]/api/users/image

변경 후
[PUT]/api/users
{
file
file(formData) | file

jwt 
*string(header) | JWT Token

nickName
string(query) |  
}
